In [50]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import numpy as np
from sklearn.model_selection import train_test_split
import warnings
warnings.simplefilter("ignore")
pd.set_option('display.max_columns', None)

result_df = pd.read_csv('formula-1-world-championship-1950-2020/results.csv')
stats_df = pd.read_csv('formula-1-world-championship-1950-2020/status.csv')
drivers_df = pd.read_csv('formula-1-world-championship-1950-2020/drivers.csv')
races_df = pd.read_csv('formula-1-world-championship-1950-2020/races.csv')
constructor_df = pd.read_csv('formula-1-world-championship-1950-2020/constructors.csv')
driver_standings_df = pd.read_csv('formula-1-world-championship-1950-2020/driver_standings.csv')
pd.get_option("display.max_columns",None)

In [51]:
result_df.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

In [52]:
stats_df.head()

   statusId        status
0         1      Finished
1         2  Disqualified
2         3      Accident
3         4     Collision
4         5        Engine

In [53]:
drivers_df.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [54]:
races_df.head()

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [55]:
constructor_df.head()

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

In [56]:
driver_standings_df.head()

   driverStandingsId  raceId  driverId  points  position positionText  wins
0                  1      18         1    10.0         1            1     1
1                  2      18         2     8.0         2            2     0
2                  3      18         3     6.0         3            3     0
3                  4      18         4     5.0         4            4     0
4                  5      18         5     4.0         5            5     0

In [57]:
races_df = races_df[['raceId', 'year', 'round', 'circuitId']]
races_df['raceId'] = races_df['raceId'].astype(int)

In [58]:
df = (
    result_df
    .merge(races_df, on='raceId')
    .merge(drivers_df, on='driverId')
    .merge(driver_standings_df, on=['driverId','raceId']) #This line right here was the one that I added raceId
    .merge(constructor_df, on='constructorId')
    .merge(stats_df, on='statusId')
)
df.head()

,resultId,raceId,driverId,constructorId,number_x,grid,position_x,positionText_x,positionOrder,points_x,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,year,round,circuitId,driverRef,number_y,code,forename,surname,dob,nationality_x,url_x,driverStandingsId,points_y,position_y,positionText_y,wins,constructorRef,name,nationality_y,url_y,status
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,2008,1,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton,1,10.0,1,1,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,Finished
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1,2008,1,1,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld,2,8.0,2,2,0,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber,Finished
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1,2008,1,1,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg,3,6.0,3,3,0,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,Finished
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1,2008,1,1,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso,4,5.0,4,4,0,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...,Finished
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1,2008,1,1,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen,5,4.0,5,5,0,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,Finished

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26290 entries, 0 to 26289
Data columns (total 39 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   resultId           26290 non-null  int64
 1   raceId             26290 non-null  int64
 2   driverId           26290 non-null  int64
 3   constructorId      26290 non-null  int64
 4   number_x           26290 non-null  object
 5   grid               26290 non-null  int64
 6   position_x         26290 non-null  object
 7   positionText_x     26290 non-null  object
 8   positionOrder      26290 non-null  int64
 9   points_x           26290 non-null  float64
 10  laps               26290 non-null  int64
 11  time               26290 non-null  object
 12  milliseconds       26290 non-null  object
 13  fastestLap         26290 non-null  object
 14  rank               26290 non-null  object
 15  fastestLapTime     26290 non-null  object
 16  fastestLapSpeed    26290 non-null  object
 17  statusId           26290 non-null  int64
 18  year               26290 non-null  int64
 19  round              26290 non-null  int64
 20  circuitId          26290 non-null  int64
 21  driverRef          26290 non-null  object
 22  number_y           26290 non-null  object
 23  code               26290 non-null  object
 24  forename           26290 non-null  object
 25  surname            26290 non-null  object
 26  dob                26290 non-null  object
 27  nationality_x      26290 non-null  object
 28  url_x              26290 non-null  object
 29  driverStandingsId  26290 non-null  int64
 30  points_y           26290 non-null  float64
 31  position_y         26290 non-null  int64
 32  positionText_y     26290 non-null  object
 33  wins               26290 non-null  int64
 34  constructorRef     26290 non-null  object
 35  name               26290 non-null  object
 36  nationality_y      26290 non-null  object
 37  url_y              26290 non-null  object
 38  status             26290 non-null  object
dtypes: float64(2), int64(14), object(23)
memory usage: 7.8+ MB

In [60]:
df.isna().sum()

resultId             0
raceId               0
driverId             0
constructorId        0
number_x             0
grid                 0
position_x           0
positionText_x       0
positionOrder        0
points_x             0
laps                 0
time                 0
milliseconds         0
fastestLap           0
rank                 0
fastestLapTime       0
fastestLapSpeed      0
statusId             0
year                 0
round                0
circuitId            0
driverRef            0
number_y             0
code                 0
forename             0
surname              0
dob                  0
nationality_x        0
url_x                0
driverStandingsId    0
points_y             0
position_y           0
positionText_y       0
wins                 0
constructorRef       0
name                 0
nationality_y        0
url_y                0
status               0
dtype: int64

In [61]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
resultId,26290.0,13539.953480,7690.546060,1.0,7014.25,13602.5,20181.75,26764.0
raceId,26290.0,557.686725,312.349538,1.0,311.00,538.0,815.00,1144.0
driverId,26290.0,282.351541,283.708052,1.0,60.00,173.0,404.00,862.0
constructorId,26290.0,50.699011,61.923927,1.0,6.00,25.0,63.00,215.0
grid,26290.0,11.093724,7.189186,0.0,5.00,11.0,17.00,34.0
positionOrder,26290.0,12.685318,7.661631,1.0,6.00,12.0,18.00,39.0
points_x,26290.0,2.023091,4.381672,0.0,0.00,0.0,2.00,50.0
laps,26290.0,46.731038,29.468480,0.0,24.00,53.0,67.00,200.0
statusId,26290.0,17.139140,25.998409,1.0,1.00,10.0,14.00,141.0
year,26290.0,1991.294066,20.095292,1950.0,1977.00,1991.0,2009.00,2024.0
round,26290.0,8.603309,5.046634,1.0,4.00,8.0,12.00,24.0
circuitId,26290.0,24.008102,19.155803,1.0,9.00,18.0,34.00,80.0
driverStandingsId,26290.0,41688.657969,23756.416372,1.0,18115.25,50319.5,64612.75,73270.0
points_y,26290.0,19.124156,43.855519,0.0,0.00,3.0,17.00,575.0
position_y,26290.0,14.525865,10.882790,1.0,7.00,13.0,20.00,105.0
wins,26290.0,0.359490,1.168250,0.0,0.00,0.0,0.00,19.0

In [62]:
columns_to_drop = [
    'url_y','url_x','position_x','fastestLapTime','positionText_x','time','driverRef',
    'constructorRef','nationality_y','positionText_y','points_y', 'number_y', 'nationality_x', 'points_x', 'status', 'code', 'position_y'
]


df = df.drop(columns=[col for col in columns_to_drop if col in df.columns])

In [63]:
df.head()

,resultId,raceId,driverId,constructorId,number_x,grid,positionOrder,laps,milliseconds,fastestLap,rank,fastestLapSpeed,statusId,year,round,circuitId,forename,surname,dob,driverStandingsId,wins,name
0,1,18,1,1,22,1,1,58,5690616,39,2,218.300,1,2008,1,1,Lewis,Hamilton,1985-01-07,1,1,McLaren
1,2,18,2,2,3,5,2,58,5696094,41,3,217.586,1,2008,1,1,Nick,Heidfeld,1977-05-10,2,0,BMW Sauber
2,3,18,3,3,7,7,3,58,5698779,41,5,216.719,1,2008,1,1,Nico,Rosberg,1985-06-27,3,0,Williams
3,4,18,4,4,5,11,4,58,5707797,58,7,215.464,1,2008,1,1,Fernando,Alonso,1981-07-29,4,0,Renault
4,5,18,5,1,23,3,5,58,5708630,43,1,218.385,1,2008,1,1,Heikki,Kovalainen,1981-10-19,5,0,McLaren