In [114]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import numpy as np
from datetime import datetime
from sklearn.model_selection import train_test_split
import warnings
warnings.simplefilter("ignore")

### Dataset Initialization

In [115]:
result_df = pd.read_csv('formula-1-world-championship-1950-2020/results.csv')
#stats_df = pd.read_csv('formula-1-world-championship-1950-2020/status.csv')
qualifying_df = pd.read_csv('formula-1-world-championship-1950-2020/qualifying.csv')
pit_stops_df = pd.read_csv('formula-1-world-championship-1950-2020/pit_stops.csv')
drivers_df = pd.read_csv('formula-1-world-championship-1950-2020/drivers.csv')
races_df = pd.read_csv('formula-1-world-championship-1950-2020/races.csv')
constructor_df = pd.read_csv('formula-1-world-championship-1950-2020/constructors.csv')
driver_standings_df = pd.read_csv('formula-1-world-championship-1950-2020/driver_standings.csv')
constructor_standings_df = pd.read_csv('formula-1-world-championship-1950-2020/constructor_standings.csv')
circuits_df = pd.read_csv('formula-1-world-championship-1950-2020/circuits.csv')
lap_times_df = pd.read_csv('formula-1-world-championship-1950-2020/lap_times.csv')
sprint_results_df = pd.read_csv('formula-1-world-championship-1950-2020/sprint_results.csv')

### Dataset Information

In [116]:
datasets = {
    "Results": result_df,
    "Races": races_df,
    "Drivers": drivers_df,
    "Constructors": constructor_df,
    "Qualifying": qualifying_df,
    "Pit Stops": pit_stops_df,
    "Driver Standings": driver_standings_df,
    "Constructor Standings": constructor_standings_df,
    "Circuits": circuits_df,
    "Lap Times": lap_times_df,
    "Sprint Results": sprint_results_df
}

for name, df in datasets.items():
    print("\n" + "="*70)
    print(f"DATASET: {name}")
    print("="*70)
    df.info()

======================================================================
DATASET: Results
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26759 entries, 0 to 26758
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26759 non-null  int64
 1   raceId           26759 non-null  int64
 2   driverId         26759 non-null  int64
 3   constructorId    26759 non-null  int64
 4   number           26759 non-null  object
 5   grid             26759 non-null  int64
 6   position         26759 non-null  object
 7   positionText     26759 non-null  object
 8   positionOrder    26759 non-null  int64
 9   points           26759 non-null  float64
 10  laps             26759 non-null  int64
 11  time             26759 non-null  object
 12  milliseconds     26759 non-null  object
 13  fastestLap       26759 non-null  object
 14  rank             26759 non-null  object
 15  fastestLapTime   26759 non-null  object
 16  fastestLapSpeed  26759 non-null  object
 17  statusId         26759 non-null  int64
dtypes: float64(1), int64(8), object(9)
memory usage: 3.7+ MB

======================================================================
DATASET: Races
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1125 non-null   int64
 1   year         1125 non-null   int64
 2   round        1125 non-null   int64
 3   circuitId    1125 non-null   int64
 4   name         1125 non-null   object
 5   date         1125 non-null   object
 6   time         1125 non-null   object
 7   url          1125 non-null   object
 8   fp1_date     1125 non-null   object
 9   fp1_time     1125 non-null   object
 10  fp2_date     1125 non-null   object
 11  fp2_time     1125 non-null   object
 12  fp3_date     1125 non-null   object
 13  fp3_time     1125 non-null   object
 14  quali_date   1125 non-null   object
 15  quali_time   1125 non-null   object
 16  sprint_date  1125 non-null   object
 17  sprint_time  1125 non-null   object
dtypes: int64(4), object(14)
memory usage: 158.3+ KB

======================================================================
DATASET: Drivers
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     861 non-null    int64
 1   driverRef    861 non-null    object
 2   number       861 non-null    object
 3   code         861 non-null    object
 4   forename     861 non-null    object
 5   surname      861 non-null    object
 6   dob          861 non-null    object
 7   nationality  861 non-null    object
 8   url          861 non-null    object
dtypes: int64(1), object(8)
memory usage: 60.7+ KB

======================================================================
DATASET: Constructors
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   212 non-null    int64
 1   constructorRef  212 non-null    object
 2   name            212 non-null    object
 3   nationality     212 non-null    object
 4   url             212 non-null    object
dtypes: int64(1), object(4)
memory usage: 8.4+ KB

======================================================================
DATASET: Qualifying
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10494 entries, 0 to 10493
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      10494 non-null  int64
 1   raceId         10494 non-null  int64
 2   driverId       10494 non-null  int64
 3   constructorId  10494 non-null  int64
 4   number         10494 non-null  int64
 5   position       10494 non-null  int64
 6   q1             10494 non-null  object
 7   q2             10472 non-null  object
 8   q3             10448 non-null  object
dtypes: int64(6), object(3)
memory usage: 738.0+ KB

======================================================================
DATASET: Pit Stops
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11371 entries, 0 to 11370
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   raceId        11371 non-null  int64
 1   driverId      11371 non-null  int64
 2   stop          11371 non-null  int64
 3   lap           11371 non-null  int64
 4   time          11371 non-null  object
 5   duration      11371 non-null  object
 6   milliseconds  11371 non-null  int64
dtypes: int64(5), object(2)
memory usage: 622.0+ KB

======================================================================
DATASET: Driver Standings
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34863 entries, 0 to 34862
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driverStandingsId  34863 non-null  int64
 1   raceId             34863 non-null  int64
 2   driverId           34863 non-null  int64
 3   points             34863 non-null  float64
 4   position           34863 non-null  int64
 5   positionText       34863 non-null  object
 6   wins               34863 non-null  int64
dtypes: float64(1), int64(5), object(1)
memory usage: 1.9+ MB

======================================================================
DATASET: Constructor Standings
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13391 entries, 0 to 13390
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   constructorStandingsId  13391 non-null  int64
 1   raceId                  13391 non-null  int64
 2   constructorId           13391 non-null  int64
 3   points                  13391 non-null  float64
 4   position                13391 non-null  int64
 5   positionText            13391 non-null  object
 6   wins                    13391 non-null  int64
dtypes: float64(1), int64(5), object(1)
memory usage: 732.4+ KB

======================================================================
DATASET: Circuits
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   circuitId   77 non-null     int64
 1   circuitRef  77 non-null     object
 2   name        77 non-null     object
 3   location    77 non-null     object
 4   country     77 non-null     object
 5   lat         77 non-null     float64
 6   lng         77 non-null     float64
 7   alt         77 non-null     int64
 8   url         77 non-null     object
dtypes: float64(2), int64(2), object(5)
memory usage: 5.5+ KB

======================================================================
DATASET: Lap Times
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 589081 entries, 0 to 589080
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   raceId        589081 non-null  int64
 1   driverId      589081 non-null  int64
 2   lap           589081 non-null  int64
 3   position      589081 non-null  int64
 4   time          589081 non-null  object
 5   milliseconds  589081 non-null  int64
dtypes: int64(5), object(1)
memory usage: 27.0+ MB

======================================================================
DATASET: Sprint Results
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   resultId        360 non-null    int64
 1   raceId          360 non-null    int64
 2   driverId        360 non-null    int64
 3   constructorId   360 non-null    int64
 4   number          360 non-null    int64
 5   grid            360 non-null    int64
 6   position        360 non-null    object
 7   positionText    360 non-null    object
 8   positionOrder   360 non-null    int64
 9   points          360 non-null    int64
 10  laps            360 non-null    int64
 11  time            360 non-null    object
 12  milliseconds    360 non-null    object
 13  fastestLap      360 non-null    object
 14  fastestLapTime  360 non-null    object
 15  statusId        360 non-null    int64
dtypes: int64(10), object(6)
memory usage: 45.1+ KB

# FEATURE ENGINEERING

### Target Variable Creation

In [118]:
result_df['position_num'] = pd.to_numeric(result_df['position'], errors='coerce')
result_df['podium'] = (result_df['position_num'] <= 3).astype(int)
print(result_df['podium'].value_counts())
print(result_df['podium'].dtype)

podium
0    23363
1     3396
Name: count, dtype: int64
int64

### Feature Renaming

In [119]:
qualifying_df = qualifying_df.rename(columns={'position': 'quali_position'})
constructor_df = constructor_df.rename(columns={'nationality': 'construct_nationality'})

### Merging of Result, Races, Qualifying, Constructor, Drivers Datasets

In [120]:
df = (
    result_df
    .merge(races_df[['raceId', 'year', 'round', 'circuitId', 'name', 'date']], on='raceId', how='left')
    .merge(qualifying_df[['raceId', 'driverId', 'quali_position']], on=['raceId','driverId'], how='left')
    .merge(constructor_df[['constructorId', 'construct_nationality']], on='constructorId', how='left')
    .merge(drivers_df[['driverId', 'nationality', 'dob','forename','surname']], on='driverId', how='left')
)

In [121]:
print(list(df.columns))

['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid', 'position', 'positionText', 'positionOrder', 'points', 'laps', 'time', 'milliseconds', 'fastestLap', 'rank', 'fastestLapTime', 'fastestLapSpeed', 'statusId', 'position_num', 'podium', 'year', 'round', 'circuitId', 'name', 'date', 'quali_position', 'construct_nationality', 'nationality', 'dob', 'forename', 'surname']

In [122]:
df.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,position_num,podium,year,round,circuitId,name,date,quali_position,construct_nationality,nationality,dob,forename,surname
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,1.0,1,2008,1,1,Australian Grand Prix,2008-03-16,1.0,British,British,1985-01-07,Lewis,Hamilton
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1,2.0,1,2008,1,1,Australian Grand Prix,2008-03-16,5.0,German,German,1977-05-10,Nick,Heidfeld
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1,3.0,1,2008,1,1,Australian Grand Prix,2008-03-16,7.0,British,German,1985-06-27,Nico,Rosberg
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1,4.0,0,2008,1,1,Australian Grand Prix,2008-03-16,12.0,French,Spanish,1981-07-29,Fernando,Alonso
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1,5.0,0,2008,1,1,Australian Grand Prix,2008-03-16,3.0,British,Finnish,1981-10-19,Heikki,Kovalainen

### Feature Datatype Change

In [123]:
print(df['grid'].dtype)
print(df['dob'].dtype)
print(df['date'].dtype)

int64
object
object

In [124]:
df['grid'] = pd.to_numeric(df['grid'], errors='coerce')
df['dob'] = pd.to_datetime(df['dob'], errors='coerce')
df['date'] = pd.to_datetime(df['date'], errors='coerce')
print(df['grid'].dtype)
print(df['dob'].dtype)
print(df['date'].dtype)

int64
datetime64[ns]
datetime64[ns]

### New Feature Driver Age (in each Race)

In [125]:
df[['name','date']]

                        name       date
0      Australian Grand Prix 2008-03-16
1      Australian Grand Prix 2008-03-16
2      Australian Grand Prix 2008-03-16
3      Australian Grand Prix 2008-03-16
4      Australian Grand Prix 2008-03-16
...                      ...        ...
26754   Abu Dhabi Grand Prix 2024-12-08
26755   Abu Dhabi Grand Prix 2024-12-08
26756   Abu Dhabi Grand Prix 2024-12-08
26757   Abu Dhabi Grand Prix 2024-12-08
26758   Abu Dhabi Grand Prix 2024-12-08

[26759 rows x 2 columns]

In [126]:
df['driver_age'] = (df['date'] - df['dob']).dt.days / 365.25

### New Feature Driver Name (Combination of 2 Features)

In [127]:
df['driver_name'] = df['forename']+' '+df['surname']

In [128]:
df[['date','driver_name','driver_age']].tail(20)

            date       driver_name  driver_age
26739 2024-12-08      Lando Norris   25.070500
26740 2024-12-08      Carlos Sainz   30.269678
26741 2024-12-08   Charles Leclerc   27.145791
26742 2024-12-08    Lewis Hamilton   39.917864
26743 2024-12-08    George Russell   26.811773
26744 2024-12-08    Max Verstappen   27.189596
26745 2024-12-08      Pierre Gasly   28.835044
26746 2024-12-08   Nico Hülkenberg   37.305955
26747 2024-12-08   Fernando Alonso   43.362081
26748 2024-12-08     Oscar Piastri   23.674196
26749 2024-12-08   Alexander Albon   28.711841
26750 2024-12-08      Yuki Tsunoda   24.577687
26751 2024-12-08       Guanyu Zhou   25.527721
26752 2024-12-08      Lance Stroll   26.110883
26753 2024-12-08       Jack Doohan   21.883641
26754 2024-12-08   Kevin Magnussen   32.175222
26755 2024-12-08       Liam Lawson   22.822724
26756 2024-12-08   Valtteri Bottas   35.279945
26757 2024-12-08  Franco Colapinto   21.535934
26758 2024-12-08      Sergio Pérez   34.866530

In [ ]:
# next merging of other datasets